### PR TITLE
Upgrade theme

### PR DESCRIPTION
**Pull request by dennisreimann**
In #137 I made a mistake which leads to the indentation of the nav as well, this commit fixes that.

### CODE REVIEW

**Review by ConorOkus — APPROVED** [review]

**Comment by moneyball** [comment]
OOC why does "serve" and "squarecrypto-vuepress-devkit-theme" differ between LDK and BDK websites?

https://github.com/bitcoindevkit/bitcoindevkit.org/blob/master/package.json

**Comment by dennisreimann** [comment]
With bitcoindevkit/bitcoindevkit.org#108 I've made the same changes for BDK as well.

**Comment by moneyball** [comment]
I see. Is there any reason this isn't shared code?

**Comment by dennisreimann** [comment]
The theme is already extracted and shared between the repos. The package.json lists the dependencies of each project - that part cannot be shared and needs to exist for each project separately. 

I think it's OK like that, because the projects might have different dependencies – e.g. if BDK would have the playground code extracted and included as a dependency, there wouldn't be a reason to also have it as part of LDK too.

**Pull request merged**
