### PR TITLE
Migrate to Vuepress

### PR DESCRIPTION
**Pull request by dennisreimann**
This PR contains the basic migration and [design adaptions](https://www.figma.com/file/DrQtd4mLRi9MiZb4IzETB9/Lightning-dev-kit-site?node-id=219%3A12020). Implementation of the design isn't fully done yet, but this covers the basics so that the docs look good and are usable already .

The intention of getting the basics out was to prevent conflicts in case the docs are being worked on currently. We can discuss how to proceed and whether or not we want to already merge it to main or wait until everything is done in full. The alternative would be to create a development branch and target this with several migration PRs.

Once we merge to main, the GitHub Actions workflow will take care of deploying the docs via GitHub Pages. After having it live, we can apply for [Algolia Docsearch](https://docsearch.algolia.com/docs/apply), which will be a major enhancement of the search. The current search just covers the headline content, Algolia does fulltext search.

The [linkcheck failure](https://github.com/lightningdevkit/lightningdevkit.org/pull/46/checks?check_run_id=2945992791) is due to a bug in rustc, the referenced docs don't build currently. Matt said we'll wait for them to fix that bug.

### CODE REVIEW

**Comment by valentinewallace** [comment]
Hmm, so it's important that it's very easy and obvious for people to get to the "Build a  Node" guides. Maybe we could replace the "Getting Started" tab with a "Guides" tab ([here](https://i.imgur.com/Kwz8lkx.png)), that goes straight to the `Build a Node in Java` guide? (and have the Rust guide listed below in the big white space [here](https://i.imgur.com/riY7jfM.png)).

Then the "Use Cases" page could go in the big white gap [here](https://i.imgur.com/VeUxKBz.png). 

Open to any ideas though!

**Comment by valentinewallace** [comment]
So, for the code samples in the guide, could we allow 80 characters before having a horizontal scroll bar? On the current website, 80 characters fit: https://i.imgur.com/a4gmAVM.png but on the new website, there's currently a scrollbar even when I have the window maximized: https://i.imgur.com/b87pvtv.png

**Comment by valentinewallace** [comment]
Bit picky, but in the current website's dark mode, code stuff has a cool "highlight": https://i.imgur.com/Slhb769.png vs it doesn't seem like the new website has that: https://i.imgur.com/a0SE3ia.png

**Comment by dennisreimann** [comment]
@valentinewallace Thanks for the feedback. I've addressed the mentioned points and added a proper sidebar, which now contains the links to the general docs and guides.

**Comment by valentinewallace** [comment]
Thank you Dennis, will give this another review today

**Comment by valentinewallace** [comment]
This looks really good! Just a few minor nits:

* Could we just rename: https://i.imgur.com/3tOpamO.png "Overview" to "Docs"? 
* Could we get rid of the `Introduction` on the homepage: https://i.imgur.com/xtJhUoY.png
* Could we make `To jump into...` copy the same font size as `Introduction`: https://i.imgur.com/33VbNwr.png

**Comment by dennisreimann** [comment]
@valentinewallace Updated according to your points :)

**Review by valentinewallace — APPROVED** [review]

**Pull request merged**
